# Generated by Django 5.1.1 on 2026-08-01 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.PositiveIntegerField(default=4)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('cupo', models.PositiveIntegerField(default=30)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academico.materia')),
            ],
        ),
    ]
