# Generated by Django 5.1.1 on 2026-08-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_group_docente_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
