# Generated by Django 5.1.1 on 2026-08-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_grupo_activo_materia_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='facultad',
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='academico.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.carrera'),
            preserve_default=False,
        ),
    ]
