# Generated by Django 5.1.1 on 2026-08-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
