# Generated by Django 5.1.1 on 2026-08-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_remove_materia_facultad_carrera_materia_carrera'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='academico.carrera'),
        ),
        migrations.AddField(
            model_name='docente',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='academico.facultad'),
        ),
    ]
